#!/bin/bash

# Setup symbolic links to this configuration directory
ln -sf /home/$USER/config/.bashrc /home/$USER/.bashrc
ln -sf /home/$USER/config/.bash_aliases /home/$USER/.bash_aliases
ln -sf /home/$USER/config/.emacs /home/$USER/.emacs
ln -sf /home/$USER/config/.Xresources /home/$USER/.Xresources
