#!/bin/bash

# Find out what type of Linux this is
if grep NAME /etc/os-release | grep Ubuntu; then
   RELEASE="Ubuntu"
   INSTALL_APP="apt-get"
   echo $RELEASE
elif grep NAME /etc/os-release | grep CentOS; then
   RELEASE="CentOS"
   INSTALL_APP="yum"
   echo $RELEASE
fi

# Update all Ubuntu packages
sudo $INSTALL_APP update
sudo $INSTALL_APP upgrade

# Make sure packages are installed
declare -a pkgs=("emacs" "mesa-utils" "git" "curl" "xauth" "x11-apps"
		 "build-essential" "xterm")
for pkg_name in "${pkgs[@]}"; do
    PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $pkg_name | grep "install ok installed")
    echo Checking for $pkg_name: $PKG_OK
    if [ "" == "$PKG_OK" ]; then
       echo "No $pkg_name. Setting up $pkg_name."
       sudo $INSTALL_APP -yes install $pkg_name
    fi
done
